import React from 'react'
import '../Styles/BlogsContainer.css'
import BlogsCard from '../Components/BlogsCard';

function BlogsContainer() {
    const blogs = [
        {
            id: 1,
            title: 'Flowers Of Drivel',
            writer: 'Shivam',
            description: `This year there is no theme for the contest. All topics are welcome.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'
        },
        {
            id: 2,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `Please ensure your entry adheres closely to the 1000-2000 word range to maximize your chances of winning!`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'
        },
        {
            id: 3,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `There is no submission fee for this year's contest. However, only one submission per individual is allowed.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
        {
            id: 4,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `Sure, if your poem(s) tell a story, we would love to read your work.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
        {
            id: 5,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `As long as there is a compelling unified narrative, we are happy to receive your entry.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
        {
            id: 6,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `You will be notified if your entry has made the shortlist and invited to the SNIoE campus for a day of creative writing workshops with our distinguished jury.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
        {
            id: 7,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `This year we require all entrants to submit a Government of India approved identity proof.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
        {
            id: 8,
            title: 'Flowers Of Drivel',
            writer: 'Shivam Gupta',
            description: `To begin the application process, please click on the Login button located in the navigation bar, and sign up using either your email address or phone number. Once you have successfully logged in, the "Enter Now" button will transform into "Apply Now". Click on the "Apply Now" button and fill out the necessary details before submitting your work.`,
            content: '"What is the best way to get what you want?" she asked. He looked down at the ground knowing that she wouldn\'t like his answer. He hesitated, knowing that the truth would only hurt. How was he going to tell her that the best way for him to get what he wanted was to leave her? It had been a simple realization that had changed Debra\'s life perspective. It was really so simple that she was embarrassed that she had lived the previous five years with the way she measured her worth. Now that she saw what she had been doing, she could see how sad it was. That made her all the more relieved she had made the change. The number of hearts her Instagram posts received wasn\'t any longer the indication of her own self-worth.It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust. The piano sat silently in the corner of the room. Nobody could remember the last time it had been played. The little girl walked up to it and hit a few of the keys. The sound of the piano rang throughout the house for the first time in years. In the upstairs room, confined to her bed, the owner of the house had tears in her eyes. She sat deep in thought. The next word that came out o her mouth would likely be the most important word of her life. It had to be exact with no possibility of being misinterpreted. She was ready. She looked deeply into his eyes and said, "Octopus." He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence. It wasn\'t that he hated her. It was simply that he didn\'t like her much. It was difficult for him to explain this to her, and even more difficult for her to truly understand. She was in love and wanted him to feel the same way. He didn\'t, and no matter how he tried to explain to her she refused to listen or to understand.'

        },
    ];
    return (
        <div className='blogs_card_container'>
            {/* {blogs.map(({ title, description , id , writer }) => (
                <BlogsCard title={title} description={description} id = {id} writer={writer}/>
            ))} */}
            <p style={{"textAlign" : "center" , "fontSize" : "30px"}}>Coming Soon!!</p>
        </div>
    )
}

export default BlogsContainer